Accept quote
rsksmart/liquidity-provider-server pull request #63
Opened 2022-08-26 20:50 UTC by joaoiovlabs

- Accept quote implementation (It was not taken into account security validations, all business rules should be defined);
- It was accepted LIQUIDITY PROVIDER SERVER postman collection.

2022-08-30 12:07 UTC, augustoIOV requested changes

2022-08-30 12:07 UTC, augustoIOV commented on http/server.go
> +	BitcoinDepositAddressHash string `json:"bitcoinDepositAddressHash"`
why would we send this bitcoindepositaddresshash as part of the response? the user should have the address already in the quote. AFAIU the only necessary response value is the Signature.

2022-08-30 12:07 UTC, augustoIOV commented on http/server.go
> +	returnQuoteSignFunc(w, signature, req.DerivationAddress)
seems unnecessary and risky to send the derivation address back from the request.

2022-09-06 13:05 UTC, coolwather approved these changes

2022-09-06 14:17 UTC, augustoIOV approved these changes
Although I see integration tests (postman), remember that we discussed creating an end to end test scenario (it can be a tiny typescript/go project in a separate folder) that ensures all of the steps on the happy path are working.

2022-09-06 14:18 UTC, merged